### ISSUE TITLE
Error when uploading template in xml

### ISSUE THREAD

**Issue by jehos** [RubinLab/epadlite#198]
Hi,

I successfully distributed using [epad-dist](https://github.com/RubinLab/epad-dist)
However, upload of AIM template failed.
After exporting xml using ATB, an error occurred file type was not supported.

I uploaded [sample xml](http://epad-public.stanford.edu:8080/epad/resources/templates/TestTemplate.xml) of template provided by the epad homepage, but the same error still occurred.

![image](https://user-images.githubusercontent.com/1180468/101495584-0d95a080-39ac-11eb-846a-a20ffed061dd.png)

So I uploaded it using the [test data](/RubinLab/epadlite/tree/master/test/data) included in the epadlite.

Isn't xml supported by template on the epad?

**Comment by emelalkim** [comment]
Hi, 
xml templates are not supported anymore but we support json versions of them. And we have created a commandline tool to convert them called [aimconvert](https://github.com/RubinLab/aimconvert). It works on old xml format of aims and templates and converts them to the new json format.
Let us know if you have any issues

**Comment by jehos** [comment]
Thank you for your quick response.

I was developing a kind of CAD, which was trying to result metadata into SR and Segmentation.
but, it was very difficult to make SR and Segmentation from scratch, so I looking for a tool to make SR and Segmentation dicom.
It is still not easy to make a template with ATB.
Can I get a sample of template for Chest CAD SR?
I cannot access the AIM database because i'm not a member of NCI.

There is not enough information about templates on the Internet, so I only looking at the best SR templates on nema.org, but not easy.
If you could give me some advice, I'd appreciate it...

**Comment by jehos** [comment]
It works well! 😄

```
jhsung@Gogunbuntu:~/src/epad/aimconvert$ yarn exec bin/aimconvert  xml2json ~/Downloads/TestTemplate.xml ~/Downloads/TestTemplate.json
yarn exec v1.22.5
Done processing /home/jhsung/Downloads/TestTemplate.xml
Done in 0.13s.
```

![image](https://user-images.githubusercontent.com/1180468/101500853-5cdecf80-39b2-11eb-9ee8-6661f426e24e.png)

**Comment by emelalkim** [comment]
Thanks jehos,
I'm glad it resolved your issue.
I know ATB is really hard to use. Happy to let you know that we are developing a new version of template builder. I'm hoping the first version will be available in January. 
You can join our email list for updates or check in in January
